[env:esp32c3_supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

lib_deps =
  SPI
  Wire
  h2zero/NimBLE-Arduino @ ^1.4.3
  jrowberg/I2Cdevlib-MPU6050 @ ^1.0.0

build_flags =
  -DCORE_DEBUG_LEVEL=0

; Notes:
; - Le board "ESP32 C3 SuperMini" n'existe pas toujours dans PlatformIO.
;   Si ton SuperMini a une variante différente, on ajustera "board=".
; - NimBLE-Arduino est le plus stable pour du Notify.

